### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by felixboehm** [owncloud/files_antivirus#171]
QA
- [x] create testplan and test cases https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Files_Antivirus.md
- [x] test and document in testplan #186 

Marketing
- [x] Check/Update info.xml (summary, description, etc.) https://github.com/owncloud/files_antivirus/issues/172
- [x] Find screenshot, if necessary https://github.com/owncloud/files_antivirus/issues/172

Build
- [x] Add changelog https://github.com/owncloud/files_antivirus/issues/173
- [x] bump version to 0.11.2
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] sign and build tarball
- [x] upload to marketplace
- [x] rename QA milestone to '$version' and close it

Docs
Nothing to do

**Comment by individual-it** [comment]
testing finished results in: #186

**Comment by PVince81** [comment]
currently no marketplace... the app is still bundled.

**Comment by VicDeo** [comment]
@felixboehm there is a screenshot already, is it good enough?
[screenshot](https://user-images.githubusercontent.com/991300/27660154-cbc247fe-5c5e-11e7-8245-b650c25521e6.png)

**Comment by PVince81** [comment]
@pmaier1 ^

**Comment by pmaier1** [comment]
Ready for release!
