### ISSUE TITLE
API (acceptance) tests 

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_antivirus#228]
It would be great to bootstrap api acceptance tests for files_antivirus

### Prerequisites
- [x] bootstrap drone testing + enable clamav in drone @patrickjahns
 
### Scenarios
- [x] Uploading via regular upload #232 
- [x] Uploading via old chunking #232 
- [x] Uploading via new chunking endpoint #232 
- [x] Public uploads (issue #209 ) (PR #244)
- [x] File-size limit when chunking (issue #179 ) (PR #245)

When we have basic tests implemented, this serves additionally as a basis for automated testing `files_antivirus` combined with objectstorage

**Comment by patrickjahns** [comment]
For drone - we can for now use `dinkel/clamavd` as clamav container. If needed we can fork and build it in https://github.com/owncloud-ci

**Comment by individual-it** [comment]
some mote tests in #246
closing this now?
