### ISSUE TITLE
files_antivirus 1.0.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_antivirus#385]
### Reason

- Release needed for ICAP support; #379  Allow to use a scanner class living outside the app 
- Move executable options into config.php #442 

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/file_antivirus/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/files_antivirus should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick
- [x] info.xml update https://github.com/owncloud/files_antivirus/pull/415

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/files_antivirus/issues/391

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by jnweiger** [comment]
## Issues opened while testing

* [ ] #393 - [QA] signing files_antrivirus 0.16.0 fails

**Comment by jnweiger** [comment]
# tested with 0.16.0RC1: installed succesfully at oc10.6.0

Setup done for 
* internal clamav
* icap docker clamav cicap

TODO: Kaspersky setup. (license renewal WIP)

**Comment by jnweiger** [comment]
Testplan completed with issues. 
I recommed that at least #400 should be fixed for the release.

**Comment by DeepDiver1975** [comment]
we just merged https://github.com/owncloud/files_antivirus/pull/413 into master
this adds McAfee support - we might want to add this to docs, release notes as well as app description

@hodyroff @pmaier1 @micbar

**Comment by jnweiger** [comment]
Back to dev. 0.16.0 will not happen like this. A 1.0.0 beta is under way.

**Comment by pmaier1** [comment]
Info.xml update https://github.com/owncloud/files_antivirus/pull/415

**Comment by jnweiger** [comment]
# Issues opened while testing 1.0.0

* [ ] #422 - [QA] Field validation passing Port number > 65535 on Antivirus Configuration screen

**Comment by micbar** [comment]
Found a release bocker 

https://github.com/owncloud/files_antivirus/issues/334

**Comment by VicDeo** [comment]
well, I would advise including https://github.com/owncloud/files_antivirus/pull/426 into release
IMO crashing the whole instance after the license expiration is too much

**Comment by C0rby** [comment]
https://gitea.owncloud.services/security/files_antivirus/pulls/1 also needs to be included to the release.

**Comment by jnweiger** [comment]
@pmaier1 Do we want to pull https://github.com/owncloud/icap/pull/30/commits/a2995f22937d7c98015dfb4a2dde36cf00bb8a6a into release-1.0.0 ?

**Comment by VicDeo** [comment]
@jnweiger if i'm not mistaken https://github.com/owncloud/icap/commit/a2995f22937d7c98015dfb4a2dde36cf00bb8a6a was merged as https://github.com/owncloud/files_antivirus/pull/415

https://github.com/owncloud/files_antivirus/pull/442 is critical for release as it is port of https://gitea.owncloud.services/security/files_antivirus/pulls/1 to the app code base

also Beta 3 has the following fixes for ICAP feature:
https://github.com/owncloud/files_antivirus/issues/438
https://github.com/owncloud/files_antivirus/issues/433

**Comment by jnweiger** [comment]
## Changlog Testing with 1.0.0-rc2

* [ ] Prevent upload virus file with new public WebDAV API - [#334](https://github.com/owncloud/files_antivirus/pull/334)
* [x] Prefer daemon or socket to executable mode if any of those is available [#399](https://github.com/owncloud/files_antivirus/pull/399)
* [x] fix: handle McAfee response [#413](https://github.com/owncloud/files_antivirus/pull/413)
* [x] Update info.xml for initial release #415
* [x] docs: fix icap setup - [#417](https://github.com/owncloud/files_antivirus/pull/426)
* [x] [QA] The system becomes unresponsive when ClamAV service has stopped #419
* [x] Improve validation pattern to check whether port number is in [1, 65535] range #423
* [x] Prevent from crashing on missing or expired license [#426](https://github.com/owncloud/files_antivirus/pull/426)
* [x] Hide ICAP-specific options if mode is not ICAP #440
* [x] Do not scan an empty content in ICAP mode #441
* [ ] Move executable options into config.php #442 (aka https://gitea.owncloud.services/security/files_antivirus/pulls/1 )

**Comment by jnweiger** [comment]
# Issues opened while testing 1.0.0

* [x] #422 - [QA] Field validation passing Port number > 65535 on Antivirus Configuration screen
Fixed with https://github.com/owncloud/files_antivirus/pull/423

**20210520**

* [ ] [QA] add files_antivirus.av_* variables to docs -  https://github.com/owncloud/docs/issues/3586
* [ ] [QA] McAfee takes 20sec per file - https://github.com/owncloud/enterprise/issues/4580
* [ ] [QA] cannot upload files larger than ca. 20 MB - https://github.com/owncloud/files_antivirus/issues/443

**Comment by mmattel** [comment]
- As we have now updated docs reflecting the changes, you should rethink if you want to describe settings in the UI or pointing to docs. Atm, the text looks akward as is is multiline and has a non professional look.
- The Mcafee setting was taking all values to work, not only the particular highlighted one.

For both, there was a chat discussion with @jnweiger during writing the docs.

**Comment by pmaier1** [comment]
![Screenshot from 2021-06-07 11-11-00](https://user-images.githubusercontent.com/21193500/120990669-13184b80-c781-11eb-8fb5-77bd6a196ec8.png)

I guess you are referring to this one. I agree that we should remove the specific configuration hints and point to the docs. Anyway, this is cosmetic, not a blocker for the release. Let's fix it afterwards.
